# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myarticles.methods


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylinks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mymedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('catch', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mymedia.MediaFile')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=(models.Model, myarticles.methods.Article),
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False)),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
                'ordering': ['article', 'order'],
            },
            bases=(models.Model, myarticles.methods.Element),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('mediafile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymedia.MediaFile')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('image_url', models.URLField(blank=True, default=None, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mylinks.Page')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('url', models.URLField()),
                ('texts', models.TextField()),
                ('source', models.TextField()),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymedia.Album')),
            ],
            options={
                'verbose_name': 'Slide',
                'verbose_name_plural': 'Slides',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Subsection',
                'verbose_name_plural': 'Subsections',
            },
            bases=('myarticles.element',),
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('element_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myarticles.Element')),
                ('texts', models.TextField()),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
            },
            bases=('myarticles.element',),
        ),
        migrations.AddField(
            model_name='element',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myarticles.Article'),
        ),
    ]
