# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('myarticles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(default='Section', max_length=100),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='title',
            field=models.CharField(default='Subsection', max_length=100),
        ),
    ]
