{% include "articles/element/vue/myarticles_article.js" %}
{% include "articles/element/vue/myarticles_section.js" %}
{% include "articles/element/vue/myarticles_subsection.js" %}
{% include "articles/element/vue/myarticles_image.js" %}
{% include "articles/element/vue/myarticles_link.js" %}
{% include "articles/element/vue/myarticles_location.js" %}
{% include "articles/element/vue/myarticles_quote.js" %}
{% include "articles/element/vue/myarticles_slide.js" %}
{% include "articles/element/vue/myarticles_text.js" %}
